apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "scania-podinfo-demo-42"
  annotations:
    "humanitec.com/orgId": "htc-demo-13"
    "humanitec.com/appId": "scania-podinfo-demo-42"
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
